Replace unknown constant with boolean
The 'False' is an unknown constant:
 NameError: uninitialized constant OVIRT::Client::False

Also the method expects the provided value to be resolved to a string,
so it can be concatenated to the request to be sent.

Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1506547